/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRoute } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LineNameRouteImport } from './routes/line.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const LineNameRoute = LineNameRouteImport.update({
  id: '/line/$name',
  path: '/line/$name',
  getParentRoute: () => rootRoute,
} as any)

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRoute
    }
    '/line/$name': {
      id: '/line/$name'
      path: '/line/$name'
      fullPath: '/line/$name'
      preLoaderRoute: typeof LineNameRouteImport
      parentRoute: typeof rootRoute
    }
  }
}

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/line/$name': typeof LineNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/line/$name': typeof LineNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/line/$name': typeof LineNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/line/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/line/$name'
  id: '__root__' | '/' | '/line/$name'
  fileRoutesById: FileRoutesById
}

export const routeTree = rootRoute
  ._addFileChildren({
    IndexRoute,
    LineNameRoute,
  })
  ._addFileTypes<FileRouteTypes>()
